spring:
  application:
    name: tcp-client

  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

tcp:
  server:
    host: isit.my.to
    port: 6998

logging:
  level:
    org.springframework.integration.ip.tcp: DEBUG